version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Boost
          command: 'sudo apt-get update && sudo apt-get install -y libboost-all-dev'
      - run:
          name: "Pull Submodules"
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'   
      - run:
          name: Artifact Binary Files
          command: |
            mkdir -p /tmp/artifacts;
            cp /tmp/trainingdata-tool/trainingdata-tool* /tmp/artifacts/;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
